"""Add conversations and messages for AI chat history

Revision ID: 0002f24253f0
Revises: 0002_add_new_features
Create Date: 2026-02-25 22:10:17.033048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002f24253f0'
down_revision: Union[str, Sequence[str], None] = '0002_add_new_features'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()

    if bind.dialect.name == 'postgresql':
        user_role_enum = sa.Enum('USER', 'ADMIN', 'MODERATOR', name='userrole')
        user_role_enum.create(bind, checkfirst=True)

    op.create_foreign_key(None, 'chat_messages', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    op.alter_column('place_images', 'is_primary',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))

    op.alter_column('places', 'review_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))

    op.create_foreign_key(None, 'search_history', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # 🔥 FIX STARTS HERE
    op.execute("ALTER TABLE users ALTER COLUMN role DROP DEFAULT")

    op.alter_column(
        'users',
        'role',
        existing_type=sa.VARCHAR(),
        type_=sa.Enum('USER', 'ADMIN', 'MODERATOR', name='userrole'),
        existing_nullable=False,
        postgresql_using="role::userrole"
    )

    op.execute("ALTER TABLE users ALTER COLUMN role SET DEFAULT 'USER'")
    # 🔥 FIX ENDS HERE


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('USER', 'ADMIN', 'MODERATOR', name='userrole'),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               existing_server_default=sa.text("'user'::character varying"))
    op.drop_constraint(None, 'search_history', type_='foreignkey')
    op.alter_column('places', 'review_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('place_images', 'is_primary',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    # ### end Alembic commands ###
