"""Add social media URLs to places

Revision ID: 15d0111cf229
Revises: 65042ae01cc6
Create Date: 2026-03-14 14:33:29.808765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15d0111cf229'
down_revision: Union[str, Sequence[str], None] = '65042ae01cc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('places', sa.Column('instagram_url', sa.String(), nullable=True))
    op.add_column('places', sa.Column('facebook_url', sa.String(), nullable=True))
    op.add_column('places', sa.Column('whatsapp_number', sa.String(), nullable=True))
    op.add_column('places', sa.Column('tiktok_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('places', 'tiktok_url')
    op.drop_column('places', 'whatsapp_number')
    op.drop_column('places', 'facebook_url')
    op.drop_column('places', 'instagram_url')
    # ### end Alembic commands ###
