"""create interactions table

Revision ID: 65042ae01cc6
Revises: 4f891e2a5942
Create Date: 2026-03-13 16:29:38.292287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65042ae01cc6'
down_revision: Union[str, Sequence[str], None] = '4f891e2a5942'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('place_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interactions_id'), 'interactions', ['id'], unique=False)
    # Defensive index drops to handle existing DB state inconsistencies
    op.execute("DROP INDEX IF EXISTS idx_chat_messages_user_id")
    op.execute("DROP INDEX IF EXISTS idx_favorites_user_id")
    op.execute("DROP INDEX IF EXISTS idx_places_category_id")
    op.execute("DROP INDEX IF EXISTS idx_places_location_gist")
    op.execute("DROP INDEX IF EXISTS idx_places_location")
    op.create_index('idx_places_location', 'places', ['location'], unique=False, postgresql_using='gist')
    op.execute("DROP INDEX IF EXISTS ix_places_owner_id")
    op.create_index(op.f('ix_places_owner_id'), 'places', ['owner_id'], unique=True)
    op.execute("DROP INDEX IF EXISTS idx_reviews_place_id")
    op.execute("DROP INDEX IF EXISTS idx_reviews_user_id")
    op.execute("DROP INDEX IF EXISTS idx_search_history_user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_search_history_user_id'), 'search_history', ['user_id'], unique=False)
    op.create_index(op.f('idx_reviews_user_id'), 'reviews', ['user_id'], unique=False)
    op.create_index(op.f('idx_reviews_place_id'), 'reviews', ['place_id'], unique=False)
    op.drop_index(op.f('ix_places_owner_id'), table_name='places')
    op.create_index(op.f('ix_places_owner_id'), 'places', ['owner_id'], unique=False)
    op.drop_index('idx_places_location', table_name='places', postgresql_using='gist')
    op.create_index(op.f('idx_places_location'), 'places', ['latitude', 'longitude'], unique=False)
    op.create_index(op.f('idx_places_location_gist'), 'places', ['location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('idx_places_category_id'), 'places', ['category_id'], unique=False)
    op.create_index(op.f('idx_favorites_user_id'), 'favorites', ['user_id'], unique=False)
    op.create_index(op.f('idx_chat_messages_user_id'), 'chat_messages', ['user_id'], unique=False)
    op.drop_index(op.f('ix_interactions_id'), table_name='interactions')
    op.drop_table('interactions')
    # ### end Alembic commands ###
