"""Add place images table and update schema

Revision ID: caa77e3627b2
Revises: 15d0111cf229
Create Date: 2026-03-14 15:17:53.706669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caa77e3627b2'
down_revision: Union[str, Sequence[str], None] = '15d0111cf229'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    op.add_column('place_images', sa.Column('image_type', sa.String(length=20), nullable=False))
    op.add_column('place_images', sa.Column('caption', sa.Text(), nullable=True))
    op.drop_column('place_images', 'is_primary')
    # op.drop_index(op.f('idx_users_location'), table_name='users', postgresql_using='gist')
    # op.drop_column('users', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('users', sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', _spatial_index_reflected=True), autoincrement=False, nullable=True))
    # op.create_index(op.f('idx_users_location'), 'users', ['location'], unique=False, postgresql_using='gist')
    op.add_column('place_images', sa.Column('is_primary', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.drop_column('place_images', 'caption')
    op.drop_column('place_images', 'image_type')
    # op.create_table('spatial_ref_sys',
    # sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    # sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    # sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    # )
    # ### end Alembic commands ###
