"""Add user_lat user_lon and cluster_id to interactions

Revision ID: d31eb022e1f2
Revises: a5eb9af09a07
Create Date: 2026-03-15 13:18:30.131978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd31eb022e1f2'
down_revision: Union[str, Sequence[str], None] = 'a5eb9af09a07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    op.add_column('interactions', sa.Column('user_lat', sa.Float(), nullable=True))
    op.add_column('interactions', sa.Column('user_lon', sa.Float(), nullable=True))
    op.add_column('interactions', sa.Column('cluster_id', sa.Integer(), nullable=True))
    # op.drop_index(op.f('idx_users_location'), table_name='users', postgresql_using='gist')
    # op.drop_column('users', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('users', sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', _spatial_index_reflected=True), autoincrement=False, nullable=True))
    # op.create_index(op.f('idx_users_location'), 'users', ['location'], unique=False, postgresql_using='gist')
    op.drop_column('interactions', 'cluster_id')
    op.drop_column('interactions', 'user_lon')
    op.drop_column('interactions', 'user_lat')
    # op.create_table('spatial_ref_sys',
    # sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    # sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    # sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    # )
    # ### end Alembic commands ###

